namespace Huppy.Core.Lib
{
    public static class Logo
    {
        private static readonly string logo = @"
WWWWWWWWWWWWWWWWWWk,;llllllc:;;:ld0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWNo,:llccllllllc:;;cd0NWNNXK000000000KKKXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWXc,clllllllllcllllc;;cccclccccccccccccccllodxOKNWWWWWWWWWWWWWWWWWWNNNNNNNWWWWWWWWWW
WWWWWWWWWWWWWWWNW0:,cllllllllccllllllc:,,;lxkxxxxxxxxxxxxddolc::cldOXXXXXXXXXNNNNNNNNNNNNNNNWWWWWWWW
WWWWWWWWWWWWWWWNW0;,cllc;:cllcllllllllllc:,:dxxxxxxdc::::::::::;,'',:c:::::cccclllooxOXNNNNNNNNNWWWW
WWWWWWWWWWWWWWWNWO;;cclc,':llcclcllllodddxdodxxxxxxdolooooollcccccccllllllccccccc:;;';ONXXNNNNNNWWWW
WWWWWWWWWWWWWWNNWk;;lc::,.,;,;:cloddxxxxxxxxxxxxxxxxxxxxxxxxxddollllllllllllllllccc:''okkxxxkKNNNNWW
WWWWWWWWWWWWWWNNWk,;lc;,;'';::lodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddollllllllllllc:,,,..:oooodx0NNNNNW
WWWWWWWWWWWWWWWNW0;,cclcc;,coodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoolllllllllcc:c;.'lKXXXXXNNNNNNW
WWWWWWWWWWWWWWWWW0:,lllccclodddxdl:ldxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdlllllllccccc,;:c0XXXXN0dONNNW
WWWWWWWWWWWWWWWWW0;,lllllldxdc;c:..':dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdollllllllc;,dOOKXXX0xc';oxKN
WWWWWWWWWWWWWWWWXo';llllldxxo,.'....'lxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdlclllllc,:0NXXXXNKkk:;x0XW
WWWWWWWWWWWWWWWNx,.,cllodxxxl'';;loc,cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdllllll:'dNNNNNNNNNNOo0WWW
WWWWWWWWNNWWWNWO;;;'clldxxxxo,lXXNWK:;dxxxxxxxxxxxxxxdolccllodxxxxxxxxxxxxxdlllll,;0NNNNNNNNNWNNNWWW
WWWNNNNNNNNNNWXl,oc':loxxxxxo,:doodko,lxxxxxxxxxxxxxxdc:ccc:coxxxxxxxxxxxxxxolll:':KWNNNNNWWWWNNWWWW
WWNNNNNNNNNNNNO;:xl,;ldxxxxxl,ckO0KXO::dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxllc,',lKWWWWWWWWWWWWWWW
NNNNNXXNXNNXNXo,lxo;,lxxxxxxc;OWNWWWNd,lxxxxxxxxxxxxxxxxxl:oxxxxxxxxxxxxxxxxxol:':c,c0WWWWWWWWWWWWWW
NNNNXXX0dkXXN0:':od:'cdxxxxx:;0WWWWWWXl,oxxdodxxxxxxxxxxxd;,lxxxdddxxxxxxxxxxdc,;,,,.,xXWWWWWWWWWWWW
NNXXXKKx;:xxkx;.'cxo,:dxxxxd;:KWWWWWWWKl,oxc';lxxxxxxxxxdl:,':oxl';oxxdc;loloc,;l,lOdc;dNWWWWWWWWWWW
NNXX0xol,,loxd,..:dd:,oxxxxo;,lOWWWWWWWXl,ld;';:cdxxxxddo;,;,.,cc'.'cdc'';odl;'cc,xWWNKXNWWWWWWWWWWW
NNNXXXXKl:OXXd'.';od:';lxd:,';;,ldddddddxl;cc,lxl::::;,,,'.''...,,.,:;,oOKNWNKo,':KWNN0KNNNWNWWWWWWW
NNNXXXXXxckXXk';l;;;:xl:dc'.',:;...',''.,xOc;',kNKOko:'.,;:::;;,,,.,okkXWWWNNWK:.xNNW0cdNNNNNWWWWWWW
NNNNNXXXKKXXXKkOKd',kWx;c;ck0X0c',      ,cKNOo;lKWNNWO;,:       ;';okNWWWWNNNNXl;0NNXx;lO0KNNNWWWWWW
NNNNNNNNNNNNNNNNNKc:KW0:'oKWWNo'         ,lXWNXXNWWWWx,;         ,;0WNWWWWNNNNXccKWXkc,;odONNNNNNWWW
NNNNNNNNNNNNNNNNWNl;0WNd;kWWWXc'         ,;OWWWWWWWWWk,,         ',0WNWWNWNNWNx;dNNNNKokNNNNNNNNWWWW
NNNNNNNNNNNNNNNWWWO:lXWKc:KWWNx,,        ,,OWWWWWWWWWXl',       ,,dNWWWWWWWXOo:dXNNNNNXNNNNNNNNNWWWW
NNNNNNNNNNNNNNWWWWWO:ckX0:cKWWNk:,;,,,,:,'oXWWWWWWWNWWKo:;;,,,;coONWWWXOxdolld0NNWNNNNNNNNNNNNNNNNNN
0KNNNNNNNNNNNWNNWWWWXxlloc,:ONWNXkolc:ccokXWWNWWNNWWWWWNX0OkOO0NWWWWXkccdxOKNWWWWWWNNNNNNNNNNNNNNNNN
;cx0NNNNNNNNNNNWWWWWWWNKkdol:l0NWWWWNNNNWWWWWNK00XNWWWWWWWWWWWNWWN0dclkNWWWWWWWWWWWWWNNNNNNNNNNNNNNN
,;d0NNNNNXXNNNNNWWWWWWWWWWWWKdclx0NWWNNWWWWWWNkodKWWWWWWWWWWWWXOdlcd0NWWWWWWWWWWWWWWWWWWWWWWWWWWWNNN
coNNNNNNXolKNNNNNWWWWWWWWWWWWWXkollox0KNWWWWWWWWWWWWWWWWNK0kdllldONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNK
0KXNNNNNXl:0XK00KNNWWWWWWWWWWWWWWN0kdooooodddddddddddollloodxOXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWXk
NNNNNOdoo;,cooooONNWWWWWWWWWWWWWWWWWWWNXKOOkkkx:'okkkx;:0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNN
NNNNNKkkOc;kXXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWXOc;0WWWK:'lkXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
NNNNNNNNNo;0NNNNNNNNWWWWWWWWWWWWWWWWWWWWWNKxllo:;kX0dlcodoloxKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWNNNNNNNo:0NNNNNNWWWWWWWWWWWWWWWWWWWWWN0o;:k0Xk,';:lkKXXXKkl:o0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWNNNNNK0XNNNNNWWWWWWWWWWWWWWWWWWWWNklcc,oXX0c;:,;xXXXXXXXk;ldld0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWNWWNNWWWWWWWWWWWWWWWWWWWWWWW0ccxKKc:KKl.;do;,dKXXXXO:cKKOo:o0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk:o0XXXd;oc::;ll;;:ckKXO:c0XXXX0o:oKWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk;dKXXXX0:.:ko:ll;d0o;ox::0XXXXXXXOc:OWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO;oKXXXXXXxlkKl:ol;dXXkc;o0XXXXxdKXXKd;dXWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK::0Od0XXXXXKXKccdc;dXXXKKXXXXXk;:ddoldo:lXWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo;clc,dXXXXXXX0:cxc;dXXXXXXXXXO:coodxk0KO:cKWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk;xKOkc:0XXXXXX0:lx:;dXXXXXXXX0c:OXXXXXXXX0ccKWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK:lKXXXx;dXOd0XXO;od;;xXXXXXXXKl;kKxolldk0XXO:lXWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWNo;kXXXX0c:K0::ONO;od,;kXXXXXXXd;ldccxOkolllxKx;xWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWO;oXXXXXXd;kX0c:0O;od';kXXXXXXKd;;,;oxkKXXKO0XKl:0WWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWXcc0XXXXKNk;oXX0c:l;oo';kNXXXXXkc'.:ddolcldkKXXXO;oNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWNd;kXKxooloo;lKXX0o,'ol.:OXXXXXKo';dKXXXX0xollkXXKl:0WWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWK:cKX0dooc'.'oKXXXKo'::.:OXXXXXk;cOXXXXXXXXXX0KXXXx;xWWWWWWWWWWWWWWWWWWWW
        ";
        public static void Print()
        {
            Console.WriteLine(logo);
        }
    }
}