name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies Main
        run: dotnet restore src/Main.sln
      - name: Restore dependencies Huppy
        run: dotnet restore src/Huppy/Huppy.sln
      - name: Build
        run: dotnet build src/Main.sln --no-restore
      - name: Build Huppy
        run: dotnet build src/Huppy/Huppy.sln --no-restore
      - name: Test
        run: dotnet test src/Main.sln --no-build --verbosity normal
